learning_test/basic_app/urls.py
from django.conf.urls import url
from basic_app import views
from django.contrib.auth import views as auth_views


# SET THE NAMESPACE!
app_name = 'basic_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    # url(r'^projectspage', views.projectpage,name='projectpage'),
    url(r'^service/$', views.service, name ="service"),
    url(r'^exist/$', views.exist, name = 'exist'),
    url(r'search/$', views.search,name = "search"),
    url(r'change_password/$', views.change_password,name = "change_password"),
    url(r'^update/(?P<pk>\d+)/$',views.ServiceUpdate.as_view(),name='update'),



]

learning_test/learn_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^admin/logs/$', views.logs, name = 'logs'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^logout/$',views.user_logout, name= "logout"),
    url(r'^special/$',views.special, name= "special"),
    

]

learning_test/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User,on_delete = models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username



DIRECTION_OPTIONS = (
    ('horizantal','HORIZANTAL'),
    ('vertical','VERTICAL'),
)


class ServiceInfo(models.Model):

    auto_project_id = models.AutoField(primary_key = True) 
    servicename = models.CharField(max_length=64)
    communication_text = models.CharField(max_length=64)
    things_text = models.CharField(max_length=64)
    child = models.CharField(max_length=64)
    parent = models.CharField(max_length=64)
    
    direction = models.CharField(max_length=12, choices = DIRECTION_OPTIONS)


    def __str__(self):

        return str(self.auto_project_id)

        def get_absolute_url(self):
            return reverse('basic_app:detail', kwargs = {'pk': self.auto_project_id})




# class DirectionInfo(models.Model):

#     direction = models.CharField(max_length=12, choices = DIRECTION_OPTIONS)
#     child = models.CharField(max_length=64)
#     parent = models.CharField(max_length=64)

#     def __str__(self):

#         return self.child






learning_test/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo,ServiceInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')



class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')


class ServiceForm(forms.ModelForm):

    communication_text = forms.CharField()
    things_text = forms.CharField()
    child = forms.CharField()
    parent = forms.CharField()

    class Meta():
        model = ServiceInfo
        fields = ('servicename', 'communication_text', 'things_text','direction', 'child', 'parent')


# class DirectionForm(forms.ModelForm):

#     # direction = forms.CharField()

#     class Meta():
#         model = DirectionInfo
#         fields = ('direction', 'child', 'parent')





learning_test/basic_app/views.py
from django.shortcuts import render, redirect
from basic_app.forms import (
    UserForm,
    UserProfileInfoForm,
    ServiceForm,
    )
from basic_app.models import (
    UserProfileInfo,
    ServiceInfo,
    )
from django.contrib.auth import (
    authenticate,
    login,
    logout,
    update_session_auth_hash
    )
from django.views.generic import (
                                View, TemplateView,
                                 ListView, DetailView,
                                 CreateView, UpdateView,
                                 DeleteView)

from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib import messages
from django.urls import reverse_lazy
# from pip import django-searchbar
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect , HttpResponse
from django.contrib.auth.forms import PasswordChangeForm
from django.http import JsonResponse
import logging,traceback


# Create your views here.
logger = logging.getLogger('django')

def check_admin(user):
   return user.is_superuser

@user_passes_test(check_admin)
def logs(request):

    f = open('./logs/infologs.log', 'r')
    file_content = f.read()
    f1 = f.readlines()
 
    context = {'file_content': file_content}
    return render(request, 'basic_app/logs.html', context)



def index(request):

    logger.info('>>>>>>>>>>>>>> someone wants to see you')
    return render(request, 'basic_app/index.html' )

@login_required
def special(request):
    return HttpResponse("you arer logging in")


@login_required
def user_logout(request):
    logout(request)

    logger.info('>>>>>>>>>>>>>> user logged out')
    return HttpResponseRedirect(reverse('index'))

def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    
    msg = '>>>>>>>> viewd profile'
    logger.info({'this user saw their profile' : request.user.username})
    args = {'user': user}
    return render(request, 'basic_app/profile.html', args)

def register(request):

    registered = False
    logger.info('some user wants to login ')

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True
            logger.info('>>>>>>>>>>>>>> someone is registerd')

        else:
            # One of the forms was invalid if this else gets called.
            logger.error('Something error wrong!')
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'basic_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def user_login(request):

    logger.info('someone wants to login')

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        logger.info('>>>>>>>>>>>>>> someone is wants to login')
        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                logger.info('>>>>>>>>>>>>>> someone is logged in')
                return render(request,'basic_app/projectpage.html')
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            logger.warning("They used username: {} and password: {}".format(username,password) )
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basic_app/login.html', {})





def service(request):

    # formfilled = False
    # form = ServiceForm()
    logger.info('this user entered the service form')

    if request.method == 'POST':

        service_form = ServiceForm(data = request.POST)
        # diretion_form = DirectionForm(data = request.POST)

        if service_form.is_valid():

            service = service_form.save()
            # direction = diretion_form.save()

            service.save()
            # direction.save()

            service_form = ServiceForm()



            # formfilled = True
            logger.info('>>>>>>>>>>> user filled the form ')

        else:
            logger.warning('>>>>>>>>>>> user filled the form wrongly ')
            print(service_form.errors)

    else:

        service_form = ServiceForm()
        # diretion_form = DirectionForm()

    return render(request, 'basic_app/serviceform.html',
                            {
                                'service_form' : service_form,
                                
                            })


def exist(request):

    logger.info('>>>>>. user visited this page output.html')

    service_exist = ServiceInfo.objects.order_by('auto_project_id')
    service_dict = {'servicename' : service_exist }

    return render(request, 'basic_app/output.html',context=service_dict)

def search(request):
    logger.info('user visited search bar page ')
    if request.method == "POST":
        servicename = request.POST['servicename']

        if servicename:
            service_match = ServiceInfo.objects.filter(Q(servicename__istartswith = servicename))


            if service_match:
                logger.info("user searched a item ")
                return render(request, 'basic_app/search.html',{'servicematch' :service_match})
            else:
                logger.warning('this is searech is not fiound')
                messages.error(request,'noresult')
        else:
            return HttpResponseRedirect('basic_app/search/')

    return render(request, 'basic_app/search.html' )





def change_password(request):
    if request.method == 'POST':
        changeform = PasswordChangeForm(data =request.POST, user = request.user)

        if changeform.is_valid():
            changeform.save()
            # update_session_auth_hash(request, changeform.user)

            logger.info('>>>>>>>>>>> user changed the password')

            return redirect('index')
        else:

            logger.error('>>. thios user supplied worng password')

            return HttpResponse("Invalid login details supplied.")


        
    else:
        changeform = PasswordChangeForm(user = request.user)

        # args = {'changeform' : changeform}
        return render(request, 'basic_app/change_password.html', {'changeform' : changeform}) 



class ServiceUpdate(UpdateView):
    #logger.info('this user wants to update table ' )

    fields = ['child']
    model = ServiceInfo
    template_name = 'basic_app/service_update.html'
    success_url = reverse_lazy('basic_app:exist')    
        

learning_test/templates/basic_app/base.html
<!DOCTYPE html>

{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"  crossorigin="anonymous"> -->




    </head>
    <body>

        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{url 'front'}">django</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index'%}">admin</a></li>
                    <li><a class="navbar-link" href="{% url 'basic_app:register'%}">register</a></li>



                    {% if user.is_authenticated %}
                        <li><a  class = 'navbar-link' href="{% url 'logout' %}">logout</a></li>
                        <li><a  class = "navbar-link" href="{% url 'basic_app:change_password'%}">changepassword</a></li>


                    {% else %}
                        <li> <a class="navbar-link" href="{% url 'basic_app:user_login' %}">login </a></li>

                    {% endif %}
                </ul>
            </div>
        </nav>
        

        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

        <div class="container">

            {% block content %}
            {% endblock %}

        </div>


        
    </body>
</html>

learning_test/templates/basic_app/change_password.html
{% extends "basic_app/base.html" %}

{% load static %}


{% block content %}

<div class="container">

    <form method="POST">

    {% csrf_token %}
    {{ changeform.as_p }}
    <button type="submit">submit</button>

    </form>

</div>

{% endblock %}


learning_test/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}
{% block content %}

<!-- <link rel="stylesheet" href="{% static "basic_app/css/mystyle.css" %}"/>   -->



<div class="jumbotron">


    <h1>django </h1>
</div>

{% endblock %}

learning_test/templates/basic_app/login.html
{% extends "basic_app/base.html" %}

{% load static %}
<!-- 
{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static "basic_app/css/mystyle.css" %}">

{% endblock %} -->


  
    {% block content %}
    

    <img class="avatar" src="{% static "basic_app/images/loginavatar.jpg" %}" >

    <link rel="stylesheet" href="{% static "basic_app/css/mystyle.css" %}"/> 

    <div class="jumbotron">

        <h1>please login</h1>
        <form action="{% url 'basic_app:user_login'%}" method="POST">
            {% csrf_token %}
            <label for="username" style="color: black;">username</label>
            <input type="text" name="username" >

            <label for="password" style="color: black;">password</label>
            <input type="password" name= "password">

            <input type="submit" value="login">

            <a href="#">forgot password</a>

        </form>

    </div>


    {% endblock %}







learning_test/templates/basic_app/logs.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <div class="container">
        <h1>logs</h1>
        
        {{ file_content | linebreaks  }}
    
    </div>
    
    
</body>
</html>










learning_test/templates/basic_app/output.html
{% extends "basic_app/base.html" %}

{% load static%}

{% block content %}


<link rel="stylesheet" href="{% static "basic_app/css/output.css" %}"/>



<div class="jumbotron">

    <h1>This all are service names and their project ids</h1>

    



    <div class = "django">
        {% if servicename %}

        {{ results }}

        <table>
            <thead>
                <th>Service id</th>
                
                <th>service</th>
                
                <th>communication</th>
                
                <th>things</th>
                
                <th>diraction</th>

                <th>child </th>
            </thead>

            {% for service in servicename %}

            <tr>
                <td>{{ service.auto_project_id }}</td>
                
                <td>{{ service.servicename }}</td>
                
                <td>{{ service.communication_text }}</td>
                
                <td>{{ service.things_text }}</td>
             
                <td>{{ service.direction}}</td>

                <td><a href="{% url 'basic_app:update' service.auto_project_id %}">update</a>{{ service.child }}</td>


                
    
            </tr>
    
            {% endfor %}
        </table>

        {% else %}

        <p>no service deatails</p>

        {% endif %}




    </div>
</div>

{% endblock %}

learning_test/templates/basic_app/profile.html
{% extends "basic_app/base.html" %}


{% load static %}



{% block content %}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>

</div>


{% endblock %}

learning_test/templates/basic_app/projectpage.html
{% extends "basic_app/base.html" %}

{% load static %}

{% block content %}


<link rel="stylesheet" href="{% static "basic_app/css/projectstyle.css" %}"/>


    <div class="jumbotron">

        <h1>choose new for creating new project or choose old for load existing project</h1>
        <div class="projectpage">

            {% csrf_token %}

            <a id="first"  href="{% url 'basic_app:service' %}" >new</a>
            

            <a id="second" href="{% url 'basic_app:exist' %}">old</a>

            <a id="third" href="{% url 'basic_app:search' %}">search</a>


            
        </div>
    </div>


{% endblock %}

learning_test/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}

{% load static%}

{% block content %}

<div class="jumbotron">

    {% if registered %}
        <h1>thank  you</h1>
    {% else %}
        <h1>registere</h1>
        <h3>fill the form</h3>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" value="Register">
        </form>
    {% endif  %}
    
</div>
{% endblock %}

learning_test/templates/basic_app/search.html
{% extends "basic_app/base.html" %}

{% load static%}

{% block content %}

<div class="container">
    <h1>search bar</h1>
    <form action="{% url 'basic_app:search'%}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <div class="col-lg-5">
                <input type="text" name="servicename" class="form-control" placeholder="enter">

            </div>
            <label class="col-lg-2"></label>
            <button type="submit" class="btn btn-danger">search</button>
        </div>
    </form><br><br>

    <div>
        {% if messages %}
            <ul class="messages">
                {% for k in messages %}
                <li style="color: red;">{{ k }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div><br>
    <div style="color: blue;">

        {% if servicematch %}
            {% for service in servicematch %}
            <table border="0px" width ="300px">
                <tr>
                    <td>id</td>
                    <td>{{ service.auto_project_id }}</td>
                </tr>
                <tr>
                    <td>service_name</td>
                    <td>{{ service.servicename }}</td>
                </tr>
                <tr>
                    <td>communication</td>
                    <td>{{ service.communication_text }}</td>
                </tr>
                <tr>
                    <td>things</td>
                    <td>{{ service.things_text }}</td>
                </tr>
                <tr>
                    <td>diraction</td>
                    <td>{{ service.direction}}</td>
                </tr>
                <tr>
                    <td>child</td>
                    <td>{{ service.child }}</td>
                </tr>
                <tr>
                    <td>parent</td>
                    <td>{{ service.parent }}</td>
                </tr>
            </table>

            {% endfor %}
        {% endif %}

    </div>
</div>


{% endblock %}

learning_test/templates/basic_app/service_update.html
{% extends 'basic_app/base.html' %}

{% block content %}

<h1>

    update serfvice


</h1>

    <form method = "POST">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit"  class="btn btn-primary" value="submit">

    </form>

{% endblock %}

learning_test/templates/basic_app/serviceform.html
{% extends "basic_app/base.html" %}

{% load static %}


{% block content %}

    <div class="container">
        <div class="jumbotron">
            
                <h2>fill the service form</h2>

                <form action = "{% url 'basic_app:service' %}" method= "POST">
                    {% csrf_token %}
                    {{ service_form.as_p }}
                    <!-- {{ diretion_form.as_p }} -->
                    <!-- <label for="servicename">service name</label>
                    <input type="text" name = "servicename" >
                    <label for="communication">communication</label>
                    <textarea name="communication"  cols="30" rows="10">fill here</textarea>
                    <label for="things">things</label>
                    <textarea name="things"  cols="30" rows="10">fill here</textarea> -->


                    <input type="submit" name="" value="save">

                </form>


        </div>

    </div>

    {% endblock %}